# Generated by Django 5.2.6 on 2025-09-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
